### ISSUE TITLE
Not an issue but question - multiple versions of the same language

### ISSUE THREAD

**Issue by developer9969** [SirJohnK/LocalizationResourceManager.Maui#1]
Hi 
Thanks for this one , its really good. I have a question that does not fall into the localization area , but in a way still does.
We have an app that is a white label app and different clients have different text 

All using "en-gb"
Example LabelWelcome on MainPage   
Client A LabelWelcome  =Welcome
Client B LabelWelcome = Good Morning
Client C LabelWelcome  = Morning

do you see the pattern?   

Currently we just have one resource  I.E AppResources.resx and we copy over the individual one for each client .

Is there any way a better solution?
thanks

**Comment by SirJohnK** [comment]
Glad you like it!

I can think of a couple solutions for this.

- You could use a file based ResourceManager and override "LabelWelcome" for each customer. Either by downloading a customer specific ".resources" file or creating one on the fly with [ResourceWriter](https://learn.microsoft.com/en-us/dotnet/api/system.resources.resourcewriter).
```csharp
.UseLocalizationResourceManager(settings =>
{
    settings.AddResource(ResourceManager.CreateFileBasedResourceManager("CustomerResources", FileSystem.Current.AppDataDirectory, null));
    settings.AddResource(AppResources.ResourceManager);
    settings.RestoreLatestCulture(true);
});
```
**Note**: The order that the resources are added is important! (The library will search from "top to bottom"!)

- Another solution, that I have used, is to include all the different texts in AppResources.resx and use a Fody weaver to replace the generated ResourceManager with a custom RersourceManager that, on the fly, replaces "LabelWelcome" based on customer specific settings. For this I have use the [Substitute.Fody](https://www.nuget.org/packages/Substitute.Fody) library.

Something like this:
```csharp
[assembly: Substitute(typeof(System.Resources.ResourceManager), typeof(CustomResourceManager))]
namespace MyResources
{
    public class CustomResourceManager : ResourceManager
    {
        private static Settings settings;

        public CustomResourceManager(string baseName, System.Reflection.Assembly assembly) : base(baseName, assembly)
        {
            settings = ServiceResolver.Resolve<Settings>();
        }

        public override string GetString(string name, CultureInfo culture)
        {
            var custom = settings.GetCustomText(name);
            var text = base.GetString(string.IsNullOrEmpty(custom) ? name : custom, culture);
            return text ?? base.GetString(name, culture);
        }
    }
}
```

**Comment by developer9969** [comment]
Hi thanks for your time in replying -- let me digest it and take it from there

thanks again
