### ISSUE TITLE
using _localizationResourceManager

### ISSUE THREAD

**Issue by jrahma** [SirJohnK/LocalizationResourceManager.Maui#10]
How can I use the _localizationResourceManager without passing it as parameter to 

`public MainPage(ILocalizationResourceManager localizationResourceManager)
`

**Comment by SirJohnK** [comment]
```LocalizationResourceManager``` will be registered in DI container when ```UseLocalizationResourceManager``` is called. So you could resolve it with the ```ServiceProvider```. But then you need a reference to that...
```csharp
public MainPage(IServiceProvider serviceProvider)
{
  var resourceManager = serviceProvider.GetRequiredService<ILocalizationResourceManager>();
}
```

What is the problem with injecting ILocalizationResourceManager in your ```MainPage```?

It will be automatically be resolved when navigating to it with ```Shell```, if the page is registered in ```AppShell``` or page route is registered. If you don't use ```Shell``` you need to register AND resolve the page by your own in e.g. a NavigationService.

**Comment by SirJohnK** [comment]
Then the ```MainPage``` is not registered with DI and/or the navigation is not done with Shell.

Can you share your project or a sample project with the same layout/problem, so I can see the hole solution?

**Comment by jrahma** [comment]
Here is a sample 

[LocalizationSample.zip](https://github.com/SirJohnK/LocalizationResourceManager.Maui/files/12254403/LocalizationSample.zip)

**Comment by SirJohnK** [comment]
For the DI injection to work, you need to register the ```MainPage``` in ```MauiProgram.CreateMauiApp```.

Look at ```MauiProgram.cs``` in the sample project.
```csharp
builder.Services.AddSingleton<MainPage>();
```
After that, you can use:
```csharp
public MainPage(ILocalizationResourceManager resourceManager)
```
...or...
```csharp
public MainPage(IServiceProvider serviceProvider)
```
Don't forget to add a ```Resources File``` and register that in ```MauiProgram.CreateMauiApp```, like in the sample application.
```csharp
.UseLocalizationResourceManager(settings =>
{
    settings.AddResource(AppResources.ResourceManager);
    settings.RestoreLatestCulture(true);
});
```

**Comment by jrahma** [comment]
Yes it's wroking.

I have one few more questions:

1. Can I define the ILocalizationResourceManager and the xmlns:localization once and use it across my entire app?

2. if I am going to do it with every page and I have HomePage which is a ContentView opened from MainPage like this:

Mobile.HomePage HomePageTabView = new Mobile.HomePage();

Then how can I pass the:

`ILocalizationResourceManager resourceManager
`
Do I need to pass it with every page I am opening?

3. I need to pass it with every page then how can I pass it wth this AppShell:

`await Shell.Current.GoToAsync($"{nameof(MemberDetails)}?MemberID={(e.DataItem as HomePageData).member_id}");
`
