### ISSUE TITLE
Enhancement: return placeholder in GetValue instead of exception

### ISSUE THREAD

**Issue by droegelor** [SirJohnK/LocalizationResourceManager.Maui#11]
Hello,

I'd like to suggest a modification to the `GetValue(string text)` method in the LocalizationResourceManager.

### Current Behavior:
The method throws a NullReferenceException when a localized string isn't found:

`return value ?? throw new NullReferenceException($"{nameof(text)}: {text} not found!");`

when I use it in xaml like that:
`xmlns:loc="clr-namespace:LocalizationResourceManager.Maui;assembly=LocalizationResourceManager.Maui"`
`<Label Text="{loc:Translate  helloWorld}" />`

### Proposed Change:
Instead of throwing an exception, it might be more user-friendly to return a placeholder string:

`return value ?? $"Text:{text}";`

This approach would help avoid application crashes due to missing localization strings and instead display a placeholder, aiding in identifying the missing items.

I believe this change would enhance the overall usability of the library. Your feedback on this suggestion would be greatly appreciated.

Thank you!

**Comment by SirJohnK** [comment]
Hi! Yes, you have a good point. I will look into this and will come back with feedback/solution.

**Comment by SirJohnK** [comment]
See the above commit to development branch for my suggested solution for this.

- Add ```SuppressTextNotFoundException``` setting to suppress/deactive throwing the text not found exception.
- Add option to set a ```PlaceholderText``` displayed if text is not found.

With the new ```SuppressTextNotFoundException``` setting you can deactivate the exception and have the option to set a custom ```PlaceholderText```.

Example (will return ```string.Empty``` if resource is not found):
```csharp
.UseLocalizationResourceManager(settings =>
{
    settings.AddResource(AppResources.ResourceManager);
    settings.RestoreLatestCulture(true);
    settings.SuppressTextNotFoundException();
});
```

...or use default placeholder text (name of resource text)...
```csharp
settings.SuppressTextNotFoundException(true);
```

...or use custom placeholder text...
```csharp
settings.SuppressTextNotFoundException(true, "Text:{0}");
```

**Comment by droegelor** [comment]
Thank you! This is even better.

**Comment by SirJohnK** [comment]
Thanks!👍 This will soon come in version 1.0.5!😀
