### ISSUE TITLE
Not working in iOS release mode

### ISSUE THREAD

**Issue by AdriVergara** [SirJohnK/LocalizationResourceManager.Maui#17]
Hi, testing your solution i found out it works fine in all platforms but doesn't apply translations in RELEASE-mode builds for iOS. No problem at all in DEBUG-mode.

I am currently testing in a physical device, I will post again here if i find a workaround for this.

**Comment by SirJohnK** [comment]
@AdriVergara , thanks for letting me know. I will also look into this.

**Comment by SirJohnK** [comment]
@AdriVergara , after a quick look at this, it could be linker related. I will do some more digging but you could try to add the following to you application project file.
```csharp
<ItemGroup>
  <TrimmerRootAssembly Include="LocalizationResourceManager.Maui" />
</ItemGroup>
```
You can read more here: [Linking a .NET MAUI iOS app](https://learn.microsoft.com/en-us/dotnet/maui/ios/linking?tabs=vs)

**Comment by AdriVergara** [comment]
There's something wrong with the linker (and/or the LLVM compiler), indeed. 

I was struggling with some functionalities (not related with your manager) in my maui app in iOS (release mode), so i have been trying some different iOS project configurations like the Linker Behavior and LLVM optimizing compiler. Finally i found this setting and it started working:

![image](https://github.com/SirJohnK/LocalizationResourceManager.Maui/assets/26234592/4cdc7a72-9fbe-4533-b03d-e727ac7105b9)

I'm not able to identify the exact moment it started working, though..

Didn't try your suggestion because i just saw it now and the previous configuration seems to be working.

Thanks a lot for the fast reply,
