### ISSUE TITLE
translations not working even when i followed all steps. im using .net 8.0 with prism 

### ISSUE THREAD

**Issue by mohammedmsadiq** [SirJohnK/LocalizationResourceManager.Maui#26]
why isnt this working, even tho everything is there

`            LocalizationResourceManager.CurrentCulture = new CultureInfo("es-ES");
`
`  xmlns:localization="clr-namespace:LocalizationResourceManager.Maui;assembly=LocalizationResourceManager.Maui"
`
` 
<Label
          Margin="0,40,0,0"
          FontFamily="LatoLight"
          Text="{localization:Translate BuildVersion}"
          FontSize="12"
          HorizontalOptions="Center"
          TextColor="White"
          VerticalOptions="Start"/>
`

![Screenshot 2024-04-16 at 01 25 02](https://github.com/SirJohnK/LocalizationResourceManager.Maui/assets/48685203/9db30e89-c910-4adb-b060-668bd8bf2524)

![Screenshot 2024-04-16 at 01 27 30](https://github.com/SirJohnK/LocalizationResourceManager.Maui/assets/48685203/ce6881a8-bb13-4272-81a4-1a4abf777b6e)

_Originally posted by @mohammedmsadiq in https://github.com/SirJohnK/LocalizationResourceManager.Maui/issues/19#issuecomment-2057833550_

![Screenshot 2024-04-16 at 01 32 06](https://github.com/SirJohnK/LocalizationResourceManager.Maui/assets/48685203/a24fcc87-cb60-4438-bdee-fb7c21ec3dfc)

**Comment by SirJohnK** [comment]
Hi, @mohammedmsadiq!
- Hard to say, but based on this information, it should work.
- What happens, what's displayed?
- Can you successfully build and run the sample project in this repo?
- Can you share the files for the view, view code behind and any viewmodel?

/Regards Johan

**Comment by mohammedmsadiq** [comment]
Which version of this library are you using?
1.3.0 alpha 1
What happens, what's displayed?
the default gets displayed which is in english
Can you successfully build and run the sample project in this repo?
it build and runs fine 
Can you share the files for the view, view code behind and any viewmodel?

`public class SpalshScreenPageViewModel : ViewModelBase
{
    private IUserAccountService _userAccountService { get; set; }

    public SpalshScreenPageViewModel(BaseServices baseServices, INavigationService navigationService, IUserAccountService accountService) : base(baseServices)
    {
        this._userAccountService = accountService;
    }

    public override void OnNavigatedTo(INavigationParameters parameters)
    {
        base.OnNavigatedTo(parameters);
        checkIfUserloggedIn();
    }

    private async void checkIfUserloggedIn()
    {
        Debug.WriteLine(BlobCache.UserAccount);
        var r = LocalizationResourceManager.CurrentCulture.Name;
        try
        {
            LocalizationResourceManager.CurrentCulture = new CultureInfo("es-ES");
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            throw;
        }
        var userResult = await _userAccountService.GetLoggedInUserDetailsAsync();
        if (userResult.AccessToken == null)
        {
            GoToLoginScreen();
        }
        else
        {
            await NavigationService.NavigateAsync("NavigationPage/MasterTabbedPage");
        }
    }
}`

**Comment by SirJohnK** [comment]
Ok, nothing obvious.
- How/Where is ```ILocalizationResourceManager``` resolved? (Can you show?)
- Since 1.3.0 alpha 1 is a prerelease version, it can(!) have issues. To be sure downgrade to v1.2.1 and test.

**Comment by mohammedmsadiq** [comment]
it works now thanks for the advise

**Comment by SirJohnK** [comment]
Great! @mohammedmsadiq , what was the solution? (If you only downgraded, I need to find the issue with 1.3.0. alpha 1....)
