### ISSUE TITLE
LocalizedString does not support ILocalizationResourceManager

### ISSUE THREAD

**Issue by ASSOLI** [SirJohnK/LocalizationResourceManager.Maui#28]
Hello, we use your `LocalisationResourceManager` in our MAUI app.
We also use the `LocalisedString `in our ViewModels.

We are currently writing tests for our ViewModels and have discovered that the `LocalisedString `does not work in test environments.
This is because there are no preferences in which the `LocalisationResourceManager `can read and write its ‘CurrentLanguage’.

So our idea was to implement a `class MockLocalizationResourceManager : ILocalizationResourceManager` for the test and to pass this to the `LocalizedString` in the constructor
 `public LocalizedString(LocalizationResourceManager.Maui.LocalizationResourceManager localizationManager, Func<string> generator)` as the first parameter.

However, this is where the problem lies: the `LocalizedString `does not work with the `ILocalisationResourceManager `interface.

Our request would be to adapt the `ILocalisationResourceManager` interface 

`public interface ILocalizationResourceManager : INotifyPropertyChanged`

And a correction of the constructor 
`public LocalizedString(LocalizationResourceManager.Maui.LocalizationResourceManager localizationManager, Func<string> generator)` of the `LocalizedString `class.

`public LocalizedString(ILocalizationResourceManager localizationManager, Func<string> generator)`

**Comment by SirJohnK** [comment]
@ASSOLI , you are in luck!😃 This is already implemented in the upcoming version (1.3.0) and is already out in the prerelease NuGet version 1.3.0-alpha.3! Take it for a spin and please report back with your findings!👍

**Comment by ASSOLI** [comment]
👍 That's exactly what I need! Great!
