### ISSUE TITLE
Question about LocalizedString 

### ISSUE THREAD

**Issue by SalimiHabib** [SirJohnK/LocalizationResourceManager.Maui#3]
hi
Is it possible to use LocalizedString  in class or struct as property ?
if it possible , is there any consideration about it?
thank you

**Comment by SirJohnK** [comment]
Sure!

Look [here](https://github.com/SirJohnK/LocalizationResourceManager.Maui/blob/main/LocalizationResourceManager.Maui.Sample/MainPage.xaml.cs) in the sample project, where LocalizedString is used as property.
```c#
public LocalizedString HelloWorld { get; }
public LocalizedString CounterBtnText { get; }
public LocalizedString CurrentCulture { get; }

public MainPage(ILocalizationResourceManager resourceManager)
{
    InitializeComponent();
    this.resourceManager = resourceManager;

    HelloWorld = new(() => $"{resourceManager["Hello"]}, {resourceManager["World"]}!");
    CounterBtnText = new(() => GetCounterBtnText());
    CurrentCulture = new(() => resourceManager.CurrentCulture.NativeName);

    BindingContext = this;
}
```
Like this, you could declare LocalizedString as property in e.g. your ViewModels.

To reference these properties from XAML it looks like this:
```c#
<Label
    FontSize="32"
    HorizontalOptions="Center"
    Text="{Binding HelloWorld.Localized}" />
```
Answer your question?

**Comment by SalimiHabib** [comment]
This is great .  

There  is another question  .
is there  any way to translate small dataset (such as filter criteria for search) by using online translate service API (such as google translate) at run time ?
is it  possible  to replacing AppResources file by online translate service ?

**Comment by SirJohnK** [comment]
I could be done by building a custom ResourceManager that uses a translation service for text lookup. That could then be added and used by this plugin!
Maybe I will create a extension for this plugin that will do this. ;)
