### ISSUE TITLE
Suggestion: remove the `Platforms` folder

### ISSUE THREAD

**Issue by hansmbakker** [SirJohnK/LocalizationResourceManager.Maui#30]
The classes in the `Platforms` folder are boilerplate code and could be removed.

**Comment by SirJohnK** [comment]
Done in the latest [1.3.0-alpha.4](https://www.nuget.org/packages/LocalizationResourceManager.Maui/1.3.0-alpha.4#releasenotes-body-tab) prerelease! 😄
