### ISSUE TITLE
Question: Custom filestructure with one .resx file per screen

### ISSUE THREAD

**Issue by MLB-BIOMETRIC** [SirJohnK/LocalizationResourceManager.Maui#9]
Hi!

Thanks for creating this awesome project. :) 

I am trying to figure out how its possible to have another filestructure than the original ``AppResource.[lang].resx`` and instead have _one .resx file per screen_.

The file structure I am looking for would be something like this:
```
Resources
    - Localization
        - StartView
            - StartView.da-DK.resx
            - LoginView.en-US.resx
            - ...
        - LoginView
            - LoginView.da-DK.resx
            - LoginView.en-US.resx
            - ...
```

**Would this be possible? and if so how? Do I have to create a CustomResource manager? @SirJohnK** 

I tried adding multiple multiple resources as seen below, but I couldn't get it to work:
````csharp
settings.AddResource(Resources.Localization.StartView.StartView.ResourceManager);
settings.AddResource(Resources.Localization.QrScanView.QrScanView.ResourceManager);
settings.AddResource(Resources.Localization.ModalAbout.ModalAbout.ResourceManager);
````
and then using it in a file like this (after successfully implementing your guide from [here on how to use ContentView](https://github.com/SirJohnK/LocalizationResourceManager.Maui/issues/6#issuecomment-1469526990)
```
DeviceIDText = new(() => resourceManager["deviceid"]);
```

It seems that it is not able to find the translated text of deviceid - and I suspect its related to my AddedResources?

**Comment by MLB-BIOMETRIC** [comment]
@SirJohnK Awesome! Thank you so much. :) 

It works really great. I think that this, a long with your guide for contentview, would be great for the readme!
_If I get time, I can try to make a PR with the information explained_

Last question, would it be possible to add some kind of key to identify what file the resource manager should look at? Such that it would be possible to have both a _helloworld_ key/value pair in LoginView.locale.resx and a _helloworld_ key/value in StartView.locale.resx

````
 Text="{localization:Translate connect File=StartView}"
 ````

Maybe I could create my own _TranslateExtension_?

I hope the above makes sense!

**Comment by SirJohnK** [comment]
@MLB-BIOMETRIC , happy to help! :)

About guides for different use cases, I am planning to add a Wiki with instructions from different issues!

To answer your question about specifying what file the resource manager should look at, I need to understand why you want to structure your files/text like this:
- Why separate files per page?
- Can't you use a common file for all common texts?
- If needed, can't you name texts with page prefix? e.g. LoginView.HelloWorld, StartView.HelloWorld
- Won't this create a lot of issue when doing the translations? e.g. The need to translate the same text multiple times.
- What happens/how will you handle translation of a text that is used in all pages?

In my mind, this will become hard to manage when app grows and languages are added.
E.g. An app with 20 views and 10 languages will then have 200 resx files.

Just trying to understand! :)

**Comment by SirJohnK** [comment]
@MLB-BIOMETRIC , I understand.

We usually use a quite different solution to solve the same issues:
- One resx file for entire app
- Use the Multilingual App Toolkit (MAT) VS Extension and Editor
- MAT generates XLIFF files, a standard file format for translations and used in the translation industry.
- MAT have a editor for editing translations. Used by internal staff, both developers and non tech users.
- MAT tracks any changes made to source text, added or updated.
- MAT can import and export changes.
- MAT generates resx files when building solution.
- We export files/changes with MAT, send them to translation service provider that has their own XLIFF editor.
- We import files/changes from translation service with MAT.
- We only edit the source/natrual language resx file in VS, all other languages are edited in the MAT editor or by translation service.
- We use the comments field each text with view name/information and usecase.
- We supply screen shots, with view name, if needed.

In this way we can have one resx file per language, that is easy to handle in application, but still have an easy way of handling translation both internally and with external translations services!

MAT VS Extension: https://marketplace.visualstudio.com/items?itemName=dts-publisher.mat2022
MAT Editor: https://learn.microsoft.com/en-us/windows/apps/design/globalizing/multilingual-app-toolkit-editor-downloads
Video with Montemagno about MAT (Xamarin, but still valid): https://www.youtube.com/watch?v=DT9vswQglks
About XLIFF on Wikipedia: https://en.wikipedia.org/wiki/XLIFF

/Regards Johan
